import { sessionIdentity } from '../src/server/auth-crypto.ts';
import assert from 'node:assert/strict';
import { randomBytes } from 'node:crypto';
import test from 'node:test';
import { readFileSync } from 'node:fs';
import { PrismaClient } from '@prisma/client';
import { PrismaSessionStore } from '../src/infrastructure/auth/prisma-session-store.ts';
import { PrismaThrottleStore } from '../src/infrastructure/auth/prisma-throttle-store.ts';
import { PrismaCompanyRepository, PrismaPermissionRepository, PrismaRegisterRepository, PrismaUserRepository } from '../src/infrastructure/auth/prisma-legacy-repositories.ts';
import { WorkerPasswordVerifier } from '../src/infrastructure/auth/password-verifier.ts';
import { loadAuthConfig } from '../src/infrastructure/auth/config.ts';
import { buildKeys } from '../src/infrastructure/auth/keys.ts';
import { handleLogin } from '../src/infrastructure/auth/handlers/login.ts';
import { handleLogout } from '../src/infrastructure/auth/handlers/logout.ts';
import { handleSession } from '../src/infrastructure/auth/handlers/session.ts';
import { handleCompany } from '../src/infrastructure/auth/handlers/company.ts';
import { handleRegister } from '../src/infrastructure/pos/handlers/register.ts';
import { LIMITS, LOCK_MS, THROTTLE_PURGE_MS, WINDOW_MS } from '@koperasi/domain/auth/throttle-policy';
import { sessionContract } from './helpers/session-store-contract.mjs';
import { ENV, bodyOf, cookieOf, makeRequest } from './helpers/auth-fakes.mjs';

// Opt-in: runs against a DISPOSABLE MariaDB (never the real staging): AUTH_TEST_DATABASE_URL (kkisi_auth account),
// AUTH_TEST_LEGACY_URL (SELECT-only account), AUTH_TEST_FIXTURE (synthetic passwords generated by the seeding script).
const AUTH_URL = process.env.AUTH_TEST_DATABASE_URL, LEGACY_URL = process.env.AUTH_TEST_LEGACY_URL, FIXTURE = process.env.AUTH_TEST_FIXTURE;
const enabled = !!(AUTH_URL && LEGACY_URL && FIXTURE);
const options = { skip: enabled ? false : 'set AUTH_TEST_DATABASE_URL/AUTH_TEST_LEGACY_URL/AUTH_TEST_FIXTURE (disposable DB)' };
if (enabled) {
  for (const url of [AUTH_URL, LEGACY_URL]) {
    const u = new URL(url);
    assert.equal(u.hostname, '127.0.0.1', 'test DB must be local');
    assert.notEqual(u.port, '3307', 'refusing to run against the real staging port');
    assert.notEqual(url, process.env.DATABASE_URL_AUTH); assert.notEqual(url, process.env.DATABASE_URL);
  }
  assert.match(new URL(AUTH_URL).pathname, /kkisi_auth_staging$/); assert.match(new URL(LEGACY_URL).pathname, /kkisi_staging$/);
}
const log = () => {};
// Like the app: ONE auth client (connection_limit=8, the account is capped at 10 connections) and one legacy client.
const clients = [];
const withLimit = (url, n) => `${url}${url.includes('?') ? '&' : '?'}connection_limit=${n}`;
let sharedAuth, sharedLegacy;
const authClient = () => (sharedAuth ??= (() => { const c = new PrismaClient({ datasourceUrl: withLimit(AUTH_URL, 8) }); clients.push(c); return c; })());
const legacyClient = () => (sharedLegacy ??= (() => { const c = new PrismaClient({ datasourceUrl: LEGACY_URL }); clients.push(c); return c; })());
test.after(async () => { await Promise.all(clients.map((c) => c.$disconnect())); });
const num = (v) => Number(typeof v === 'bigint' ? Number(v) : v);

async function freshAuthDb() { const db = authClient(); await db.$executeRawUnsafe('DELETE FROM kkisi_auth_staging.auth_session'); await db.$executeRawUnsafe('DELETE FROM kkisi_auth_staging.auth_throttle'); return db; }

for (const [name, fn] of Object.entries(sessionContract)) {
  test(`REAL MariaDB session store contract: ${name}`, options, async (t) => {
    const db = await freshAuthDb();
    const make = async () => { await db.$executeRawUnsafe('DELETE FROM kkisi_auth_staging.auth_session'); const s = new PrismaSessionStore(db, log);
      s.countForUser = async (u) => num((await db.$queryRaw`SELECT COUNT(*) AS n FROM kkisi_auth_staging.auth_session WHERE user_id = ${u}`)[0].n); return s; };
    await fn(t, { make });
  });
}

test('REAL session store: 8 simultaneous logins by one user with a pool of 8 connections keep exactly 5 valid sessions, no failures', options, async () => {
  const db = authClient(); await db.$executeRawUnsafe('DELETE FROM kkisi_auth_staging.auth_session');
  const s = new PrismaSessionStore(db, log); const { createHash } = await import('node:crypto'); const now = new Date();
  const results = await Promise.allSettled(Array.from({ length: 8 }, (_, i) => s.create({ sidHash: createHash('sha256').update('c' + i).digest(), userId: 77, companyId: 1, pwf: 'bb'.repeat(8), now, idleExpiresAt: new Date(now.getTime() + 7200e3), absExpiresAt: new Date(now.getTime() + 43200e3), purgeAfter: new Date(now.getTime() + 129600e3) })));
  assert.equal(results.filter((r) => r.status === 'fulfilled').length, 8, JSON.stringify(results.filter((r) => r.status === 'rejected').map((r) => String(r.reason?.message))));
  const valid = num((await db.$queryRaw`SELECT COUNT(*) AS n FROM kkisi_auth_staging.auth_session WHERE user_id = 77 AND revoked_at IS NULL`)[0].n);
  assert.equal(valid, 5);
});

test('REAL throttle store: threshold, fixed window restart, exact counting under 100 parallel failures, cleared by success, purge bounded', options, async () => {
  const db = await freshAuthDb(); const th = new PrismaThrottleStore(db, log); const t0 = new Date('2026-10-01T08:00:00Z');
  const key = { kind: 'user', keyHash: Buffer.alloc(32, 9) };
  const rec = (now, limit = 3) => th.recordFailure({ key, limit, now, windowMs: WINDOW_MS, lockMs: LOCK_MS, purgeAfter: new Date(now.getTime() + THROTTLE_PURGE_MS) });
  await rec(t0); await rec(new Date(t0.getTime() + 120e3)); assert.deepEqual(await th.activeLocks([key], new Date(t0.getTime() + 130e3)), []);
  await rec(new Date(t0.getTime() + 240e3));
  const locks = await th.activeLocks([key], new Date(t0.getTime() + 250e3)); assert.equal(locks.length, 1); assert.equal(locks[0].lockedUntil.getTime(), t0.getTime() + 240e3 + LOCK_MS);
  await rec(new Date(t0.getTime() + 40 * 60e3));                        // after the window: counter restarts at 1
  assert.equal(num((await db.$queryRaw`SELECT failures AS n FROM kkisi_auth_staging.auth_throttle`)[0].n), 1);
  await th.clear([key]); assert.equal(num((await db.$queryRaw`SELECT COUNT(*) AS n FROM kkisi_auth_staging.auth_throttle`)[0].n), 0);
  const th2 = new PrismaThrottleStore(db, log);
  const k2 = { kind: 'user', keyHash: Buffer.alloc(32, 7) };
  await Promise.all(Array.from({ length: 100 }, () => th2.recordFailure({ key: k2, limit: LIMITS.user, now: t0, windowMs: WINDOW_MS, lockMs: LOCK_MS, purgeAfter: new Date(t0.getTime() + THROTTLE_PURGE_MS) })));
  assert.equal(num((await db.$queryRaw`SELECT failures AS n FROM kkisi_auth_staging.auth_throttle WHERE key_hash = ${k2.keyHash}`)[0].n), 100, 'no lost update');
  assert.equal((await th2.activeLocks([k2], new Date(t0.getTime() + 1000))).length, 1);
  for (let i = 0; i < 25; i++) await th.recordFailure({ key: { kind: 'ip', keyHash: Buffer.alloc(32, 20 + i) }, limit: 30, now: t0, windowMs: WINDOW_MS, lockMs: LOCK_MS, purgeAfter: new Date(t0.getTime() - 1) });
  assert.equal(await th.purge(t0, 10), 10); assert.equal(await th.purge(t0, 100), 15);
  await th.clear([k2]);
});

test('REAL throttle store: an impossible lock (10 years ahead, e.g. after a clock jump) is ignored and removed', options, async () => {
  const db = await freshAuthDb(); const th = new PrismaThrottleStore(db, log); const now = new Date('2026-10-01T08:00:00Z'); const key = { kind: 'user', keyHash: Buffer.alloc(32, 5) };
  await db.$executeRaw`INSERT INTO kkisi_auth_staging.auth_throttle (key_hash,kind,failures,first_failure_at,last_failure_at,locked_until,purge_after) VALUES (${key.keyHash},'user',10,${now},${now},${new Date('2036-10-01T08:00:00Z')},${new Date('2036-10-01T10:00:00Z')})`;
  assert.deepEqual(await th.activeLocks([key], now), []);
  assert.equal(num((await db.$queryRaw`SELECT COUNT(*) AS n FROM kkisi_auth_staging.auth_throttle WHERE key_hash = ${key.keyHash} AND locked_until IS NOT NULL AND locked_until > ${new Date('2030-01-01')}`)[0].n), 0, 'the bogus lock was removed');
});

test('REAL legacy repositories over the SELECT-only account: users, role/branch status, permissions, branches, registers, cash registers', options, async () => {
  const db = legacyClient(); const users = new PrismaUserRepository(db, log), perms = new PrismaPermissionRepository(db, log), companies = new PrismaCompanyRepository(db, log), regs = new PrismaRegisterRepository(db, log);
  const kasir1 = await users.findByUsername('SYNTH_KASIR1'); assert.equal(kasir1.roleId, 4); assert.equal(kasir1.companyId, 1); assert.equal(kasir1.roleStatus, 1); assert.equal(kasir1.companyStatus, 1); assert.match(kasir1.passwordHash, /^\$2y\$/);
  assert.equal((await users.findById(kasir1.id)).username, 'synth_kasir1');
  assert.equal((await users.findByUsername('synth_kepala')).roleStatus, 0, 'role 3 is inactive like in production');
  assert.equal((await users.findByUsername('synth_nobranch')).companyStatus, 0);
  assert.equal((await users.findByUsername('synth_off')).status, 0);
  assert.equal(await users.findByUsername('nobody'), null); assert.equal(await users.findById(-1), null);
  assert.equal(await users.findByUsername("x' OR '1'='1"), null, 'parameterised: SQL in the username is just a string');
  assert.equal(await perms.has(4, 'sales_add'), true); assert.equal(await perms.has(1, 'master_kasir'), false); assert.equal(await perms.has(4, "sales_add' OR '1'='1"), false);
  assert.deepEqual((await companies.listActive()).map((c) => c.id), [1, 2, 3]); assert.equal(await companies.findActive(4), null);
  const now = new Date();
  const open = await regs.findOpen(900004, 1, now); assert.equal(open.register.noref, 'KRS-S-1'); assert.equal(open.register.noKasir, 'KRS01'); assert.equal(open.openCount, 1); assert.equal(open.register.stale, false);
  const stale = await regs.findOpen(900005, 2, now); assert.equal(stale.register.stale, true, 'opened 2026-09-16 is a stale register');
  assert.equal((await regs.findOpen(900004, 2, now)).register, null, 'a register of another branch is never returned');
  assert.equal(await regs.hasOpenOutside(900002, 1), true); assert.equal(await regs.hasOpenOutside(900002, 2), false); assert.equal(await regs.hasOpenOutside(900001, 1), false);
  assert.deepEqual(await regs.listKasir(2), [{ id: 2, noKasir: 'KRS01' }]);
  let denied = false; try { await db.$executeRawUnsafe("UPDATE db_users SET status = status WHERE id = -1"); } catch (e) { denied = /1142|denied/i.test(String(e.message)); }
  assert.equal(denied, true, 'the legacy connection cannot write');
});

async function realWorld(extraEnv = {}) {
  const pw = JSON.parse(readFileSync(FIXTURE, 'utf8'));
  const authDb = authClient(), legacyDb = legacyClient();
  const config = loadAuthConfig({ ...ENV, DATABASE_URL: LEGACY_URL, DATABASE_URL_AUTH: AUTH_URL, ...extraEnv }); const keys = buildKeys(config.secrets);
  const logs = []; const l = (e, f) => logs.push({ e, ...f });
  const verifier = new WorkerPasswordVerifier({ workers: 2, maxQueue: 8 });
  const services = { config, keys, deps: {
    clock: { now: () => new Date() }, random: { bytes: (n) => randomBytes(n) }, identity: sessionIdentity, log: l,
    users: new PrismaUserRepository(legacyDb, l), permissions: new PrismaPermissionRepository(legacyDb, l), companies: new PrismaCompanyRepository(legacyDb, l), registers: new PrismaRegisterRepository(legacyDb, l),
    sessions: new PrismaSessionStore(authDb, l), throttle: new PrismaThrottleStore(authDb, l), verifier, throttleKeys: (u, ip) => keys.throttleKeys(u, ip) } };
  return { services, pw, logs, close: () => verifier.close(), authDb };
}
const post = (services, handler, path, body, o = {}) => handler(services, makeRequest(path, { method: 'POST', body, ...o }));

test('FULL STACK on a real MariaDB (synthetic identities): login, session, register, branch rules, logout persistence, lockout, generic failures', options, async () => {
  const world = await realWorld(); const { services, pw } = world; await freshAuthDb();
  try {
    const login = (u, p, o) => post(services, handleLogin, '/api/auth/login', { username: u, password: p }, o);
    // generic failures are byte-identical: unknown, wrong password, disabled, inactive role, inactive branch
    const shapes = new Set();
    for (const [u, p] of [['ghost', 'x'], ['synth_kasir1', 'wrong'], ['synth_off', pw.off], ['synth_kepala', pw.kepala], ['synth_nobranch', pw.nobranch]]) { const r = await login(u, p); assert.equal(r.status, 401, u); shapes.add(await r.text() + JSON.stringify([...r.headers].filter(([k]) => k !== 'set-cookie'))); }
    assert.equal(shapes.size, 1);
    assert.deepEqual(new Set(world.logs.filter((x) => x.e === 'login_failed').map((x) => x.reason)), new Set(['bad_credentials', 'role_inactive', 'company_inactive']));

    const ok = await login('synth_kasir1', pw.kasir1); assert.equal(ok.status, 200);
    const cookie = cookieOf(ok), token = (await bodyOf(ok)).csrfToken;
    const me = await bodyOf(await handleSession(services, makeRequest('/api/auth/session', { cookie })));
    assert.equal(me.user.roleId, 4); assert.equal(me.company.name, 'SYNTH BRANCH 1'); assert.equal(me.canSwitchBranch, false);
    const reg = await bodyOf(await handleRegister(services, makeRequest('/api/pos/register', { cookie })));
    assert.equal(reg.open.noref, 'KRS-S-1'); assert.deepEqual(reg.kasir, [{ id: 1, noKasir: 'KRS01' }]);
    assert.equal((await post(services, handleCompany, '/api/auth/company', { companyId: 2 }, { cookie, token })).status, 403, 'role 4 cannot change branch');

    // role <= 2: may choose a branch, but not while a register is open elsewhere
    const kop = await login('synth_koperasi', pw.koperasi); const kc = cookieOf(kop), kt = (await bodyOf(kop)).csrfToken;
    assert.equal((await post(services, handleCompany, '/api/auth/company', { companyId: 3 }, { cookie: kc, token: kt })).status, 403, 'open register in branch 2');
    assert.equal((await post(services, handleCompany, '/api/auth/company', { companyId: 2 }, { cookie: kc, token: kt })).status, 200);
    const kreg = await bodyOf(await handleRegister(services, makeRequest('/api/pos/register', { cookie: kc })));
    assert.equal(kreg.open.noref, 'KRS-S-2', 'the register read follows the SESSION branch');
    const stale = await login('synth_kasir2', pw.kasir2); const st = await bodyOf(await handleRegister(services, makeRequest('/api/pos/register', { cookie: cookieOf(stale) })));
    assert.equal(st.open.stale, true);

    // logout is persistent: a brand-new set of services (a "restart") still refuses the id
    assert.equal((await post(services, handleLogout, '/api/auth/logout', {}, { cookie, token })).status, 200);
    const restarted = await realWorld();
    try { assert.equal((await handleSession(restarted.services, makeRequest('/api/auth/session', { cookie }))).status, 401); } finally { await restarted.close(); }
    assert.equal((await handleSession(services, makeRequest('/api/auth/session', { cookie: kc }))).status, 200, 'other sessions unaffected');

    // 10 wrong passwords lock the username persistently, even for the right password; another user is unaffected
    for (let i = 0; i < 10; i++) await login('synth_admin', 'wrong' + i);
    const locked = await login('synth_admin', pw.admin); assert.equal(locked.status, 429); assert.ok(Number(locked.headers.get('retry-after')) > 0);
    assert.equal((await login('synth_kasir1', pw.kasir1)).status, 200);
    const stored = await world.authDb.$queryRaw`SELECT kind, failures FROM kkisi_auth_staging.auth_throttle`;
    assert.deepEqual([...new Set(stored.map((r) => r.kind))], ['user'], 'only user keys exist without a trusted proxy');
    for (const row of await world.authDb.$queryRaw`SELECT HEX(sid_hash) AS h FROM kkisi_auth_staging.auth_session`) assert.equal(String(row.h).length, 64);
  } finally { await world.close(); }
});
